name: ldm
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python==3.10.6
  - pip
 
  # pytorch left unpinned
  - pytorch
  - torchmetrics
  - torchvision

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/ldm/ldm-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yaml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n ldm-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations
  - coloredlogs
  - einops
  - grpcio
  - humanfriendly
  - imageio-ffmpeg
  - imageio
  - imgaug
  - kornia
  - mpmath
  - nomkl
  - numpy
  - omegaconf
  - onnx
  - onnxruntime
  - opencv
  - pudb
  - pytorch-lightning
  - scipy
  - streamlit
  - sympy
  - tensorboard
  - transformers
  - pip:
    - invisible-watermark
    - test-tube
    - tokenizers
    - torch-fidelity
    - -e git+https://github.com/huggingface/diffusers.git@v0.2.4#egg=diffusers
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
    - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
